version: '3.8'

services:
  app:
    build: .
    container_name: wallet_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://wallet-db:5432/wallet_engine
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - wallet-db
    restart: on-failure

  wallet-db:
    image: postgres:15-alpine
    container_name: wallet_postgres
    environment:
      - POSTGRES_DB=wallet_engine
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: